"""mybooking table added

Revision ID: 0bae69f7141e
Revises: 920979057281
Create Date: 2024-08-06 15:48:05.205815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bae69f7141e'
down_revision: Union[str, None] = '920979057281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mybooking',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('Booking_id', sa.String(length=50), nullable=True),
    sa.Column('Train_name', sa.String(length=30), nullable=False),
    sa.Column('Departure_from', sa.String(length=30), nullable=False),
    sa.Column('Arrival_to', sa.String(length=30), nullable=False),
    sa.Column('Departure_Time', sa.String(length=30), nullable=False),
    sa.Column('Departure_date', sa.String(length=20), nullable=False),
    sa.Column('Booked_tickets', sa.String(length=50), nullable=False),
    sa.Column('Booking_Status', sa.String(length=50), nullable=False),
    sa.Column('Booking_date', sa.String(length=40), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Booking_id'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mybooking')
    # ### end Alembic commands ###
