"""added booking table1

Revision ID: 38c1bd9de473
Revises: cf416735e02d
Create Date: 2024-07-05 17:11:02.324784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38c1bd9de473'
down_revision: Union[str, None] = 'cf416735e02d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('Departure_from', sa.String(length=30), nullable=False),
    sa.Column('Arrival_to', sa.String(length=30), nullable=False),
    sa.Column('Departure_Time', sa.String(length=30), nullable=False),
    sa.Column('Departure_date', sa.String(length=20), nullable=False),
    sa.Column('Train_class', sa.String(length=30), nullable=False),
    sa.Column('Categories', sa.String(length=40), nullable=False),
    sa.Column('Num_of_passengers', sa.String(length=20), nullable=False),
    sa.Column('Food_Available', sa.String(length=10), nullable=False),
    sa.Column('Price_of_one_ticket', sa.String(length=20), nullable=False),
    sa.Column('Total_amount', sa.String(length=20), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    # ### end Alembic commands ###
