"""Train table added

Revision ID: 70f16c7579dd
Revises: 1afef8f269ca
Create Date: 2024-08-05 14:52:11.701516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70f16c7579dd'
down_revision: Union[str, None] = '1afef8f269ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trains',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('Train_name', sa.String(length=100), nullable=False),
    sa.Column('Train_class', sa.String(length=30), nullable=False),
    sa.Column('Departure_from', sa.String(length=30), nullable=False),
    sa.Column('Arrival_to', sa.String(length=30), nullable=False),
    sa.Column('Departure_Time', sa.String(length=30), nullable=False),
    sa.Column('Departure_date', sa.String(length=20), nullable=False),
    sa.Column('Price_of_one_ticket', sa.String(length=20), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trains')
    # ### end Alembic commands ###
