"""Solve error about booking

Revision ID: 897f8a90bff3
Revises: 38c1bd9de473
Create Date: 2024-07-09 16:28:57.975280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '897f8a90bff3'
down_revision: Union[str, None] = '38c1bd9de473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('user_id', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'booking', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.drop_column('booking', 'user_id')
    # ### end Alembic commands ###
