"""changes in Train table

Revision ID: 8b7cb9f191fb
Revises: 33acf2f3b53b
Create Date: 2024-08-01 15:40:51.993921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b7cb9f191fb'
down_revision: Union[str, None] = '33acf2f3b53b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
