"""Schedule table added

Revision ID: 920979057281
Revises: 70f16c7579dd
Create Date: 2024-08-05 15:50:59.339880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '920979057281'
down_revision: Union[str, None] = '70f16c7579dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('train_id', sa.String(length=50), nullable=True),
    sa.Column('Departure_from', sa.String(length=30), nullable=False),
    sa.Column('Arrival_to', sa.String(length=30), nullable=False),
    sa.Column('Departure_Time', sa.String(length=30), nullable=False),
    sa.Column('Departure_date', sa.String(length=20), nullable=False),
    sa.Column('JourneyDuration', sa.String(length=20), nullable=False),
    sa.Column('Booked_tickets', sa.String(length=50), nullable=False),
    sa.Column('Availability', sa.String(length=20), nullable=False),
    sa.Column('Status', sa.String(length=30), nullable=False),
    sa.Column('Stations', sa.String(length=50), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule')
    # ### end Alembic commands ###
