"""update in otp table

Revision ID: d71a38bf7f2e
Revises: 77fe8a0dc3c9
Create Date: 2024-07-04 14:52:04.309556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd71a38bf7f2e'
down_revision: Union[str, None] = '77fe8a0dc3c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp', sa.Column('otp', sa.String(length=6), nullable=False))
    op.add_column('otp', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.drop_column('otp', 'is_active')
    op.drop_column('otp', 'modified_at')
    op.drop_column('otp', 'Otp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp', sa.Column('Otp', sa.VARCHAR(length=6), autoincrement=False, nullable=False))
    op.add_column('otp', sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('otp', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('otp', 'expires_at')
    op.drop_column('otp', 'otp')
    # ### end Alembic commands ###
